site_name: Postie
site_url: https://BenSBk.github.io/Postie
repo_name: BenSBk/Postie
repo_url: https://github.com/BenSBk/Postie

theme:
  name: material
  palette:
    primary: "Light Blue"
    accent: "Light Blue"

nav:
  - Home: index.md
  - API: api.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
